Update HotShot to 0.5.11
EspressoSystems/hotshot-query-service pull request #388
Opened 2024-02-01 22:41 UTC by tbro

2024-02-06 17:33 UTC, tbro commented
Addresses: https://github.com/EspressoSystems/espresso-sequencer/issues/1074

2024-02-07 20:01 UTC, nomaxg approved these changes

2024-02-07 21:31 UTC, jbearer requested changes

2024-02-07 21:31 UTC, jbearer commented on src/data_source.rs
>              // height, the numerator, is 1, and the view number, the denominator, is 0).
Comments are out of date now

2024-02-07 21:31 UTC, jbearer commented on src/status.rs
>          // The block height is initially 1 (for the genesis block).
Comment is out of date now

2024-02-07 21:34 UTC, tbro commented on src/data_source.rs
>              // height, the numerator, is 1, and the view number, the denominator, is 0).
on it

2024-02-07 22:28 UTC, tbro commented on src/status.rs
>          // The block height is initially 1 (for the genesis block).
fixed in 14883ca

2024-02-07 22:28 UTC, tbro commented on src/data_source.rs
>              // height, the numerator, is 1, and the view number, the denominator, is 0).
fixed in 14883ca

2024-02-07 22:53 UTC, jbearer commented on src/data_source.rs
> +            // Check that block height is initially zero (for the genesis block).
```suggestion
            // Check that block height is initially zero.
```

2024-02-07 22:53 UTC, jbearer commented on src/status.rs
> +        // The block height is initially zero (for the genesis block).
```suggestion
        // The block height is initially zero.
```

2024-02-08 00:47 UTC, jbearer approved these changes
Looks good, pending CI 🤞

2024-02-08 01:11 UTC, merged